// Public surface of the compiled shared-canvas Compact contract.
//
// The `managed/` directory is generated by @nyxels/contract's `compile` step
// (`compact compile`). This re-export gives consumers (the UI, tests, scripts)
// one stable import path — `@nyxels/contract-sdk` — instead of reaching into
// generated compiler output. It also leaves a home for hand-written glue (e.g.
// Stroke[] <-> Uint8Array helpers, typed witness factories) as the app grows.
export * from "../managed/contract/index.js";
export * from "./utils/dust-estimation.ts";
